### ISSUE TITLE
How to make f5c work inside a nextflow pipeline?

### ISSUE THREAD

**Issue by bhargava-morampalli** [hasindu2008/f5c#108]
Hello Dr. Gamaarachchi, 

I am trying to use f5c in a nextflow pipeline and I keep getting errors. F5c runs fine outside of pipeline but always fails inside workflow. I am not sure what I am doing wrong. I have tried asking for someone else for help but couldn’t find a solution. 

I keep getting this error - even though the f5c index process completed successfully. If you have time, can you please take a look and let me know if I am doing anything wrong?

**Command error:**
  error: could not load the index files for input file sample.fastq
  Please run f5c index on your reads (see documentation)

```
process f5cindex {

    publishDir "$params.outdir/${singlefast5s.simpleName}_single", mode:'copy'

    tag "nanopolish index using f5c"

    input:
    path singlefast5s
    path fastq
    val flag

    output:
    path "*", optional: true
    val true, emit: f5cindexout

    script:
    """
    f5c index -t 24 -d $singlefast5s $fastq
    """
}
```

```

process f5ceventalign {

    publishDir "$params.outdir/${fastq.simpleName}_f5c", mode:'copy'

    input:
    path fastq
    tuple path(bam), path(bai)
    path referencefasta
    val flag

    output:
    path "*_summary.txt", emit: f5csummary_ch
    path "*_eventalign.txt", emit: f5ceventalign_ch
    val true, emit: f5ceventaligndone_ch

    script:
    """
    f5c eventalign --scale-events --signal-index --print-read-names --rna -r $fastq -b $bam -g $referencefasta --summary ${bam.simpleName}_summary.txt --threads 40 > ${bam.simpleName}_eventalign.txt
    """
}
```

**how I defined channels?**

    Channel
    .value(file("$baseDir/sample_singlefast5s"))
    .set {singlefast5s}

    Channel
    .fromPath("$baseDir/mappedfastqs_16s_native/sample.fastq")
    .set {samplefastq}

baminput1 = [
        file("$baseDir/mappedbams_16s_native/sample.bam"),
        file("$baseDir/mappedbams_16s_native/sample.bam.bai")
]

    Channel
    .value(file(params.reference_16s))
    .set {reference}

**workflow:**

    f5cindex (singlefast5s, samplefastq)

    f5ceventalign (samplefastq, baminput1, reference)

**Comment by hasindu2008** [comment]
Hi 

I have not used nextflow before. So I might need to actually run it myself and see what is happening. Could you please attach the workflow script you have written as a text file or something here so that I can try it on my side? 
This error that the fastq is not index could be coming due to a wrong path - but need to double check by running the script.

Also I am tagging my colleague @Psy-Fer here who is perhaps familiar with nextflow.

**Comment by hasindu2008** [comment]
I went through the scripts. The problem is that the index step and the eventalign step are executed in two separate working directories. The index step creates some new files. For instance if the fastq file was reads.fastq, the following files are created by the index command:
```
reads.fastq.index
reads.fastq.index.fai
reads.fastq.index.gzi
reads.fastq.index.readdb
```

these files must be somehow copied or given to the working directory of the eventalign command. When your nextflow pipeline fails it prints the working directory as well right? If you `cd` into that directory and do `ls` you would see that the above files are not copied over to there.

**Comment by bhargava-morampalli** [comment]
Thank you for trying that out. I resolved the problem. index files were going into a different directory and even when in the correct directory, they were not getting accessed. I bound the fastq with all the index files as tuple entry similar to bam input. 

like this just in case if anyone need it. 

```
fastqinput1 = [
        file("$baseDir/data/fastqs/reads.fastq"),
        file("$baseDir/data/fastqs/reads.fastq.index"),
        file("$baseDir/data/fastqs/reads.fastq.index.fai"),
        file("$baseDir/data/fastqs/reads.fastq.index.gzi"),
        file("$baseDir/data/fastqs/reads.fastq.index.readdb")
]
```

then like this in the process input - 

`tuple path(fastq), path(index), path(fai), path(gzi), path(readdb)`
```
tuple path(bam), path(bai)
path referencefasta
```

and finally like this in workflow - 

`eventalign (fastqinput1, baminput1, reference)`

Process completes without any errors now.
