### ISSUE TITLE
few sites from LSK114

### ISSUE THREAD

**Issue by ogrecio** [hasindu2008/f5c#115]
Hi, I'm using f5c to call methylation sites from LSK114.

I'm obtaining only few sites. Is f5c ready to be used on LSK114? How should I implement f5c on reads from LSK114?

Thank you,
Oscar

**Comment by hasindu2008** [comment]
Unfortunately, we are still in the process of deriving a model for R10.4.1 (aka LSK 114). The current built-in models in f5c are for R9.4.1, so I am surprised it even picks a few sites in LSK114.

@hiruna72 is working on deriving a model - will let you know soon as we get it.

**Comment by hasindu2008** [comment]
If it goes according to the plan, like one month. But these things rarely go according to the plan :D. So I would say a couple of months.

**Comment by hasindu2008** [comment]
@ogrecio 
Sorry for the delay. Finally, we have a very crude methylation model for R10.4.1. Do you by chance have some data with a baseline suitable for testing?

**Comment by ogrecio** [comment]
Hi!
we may have some data available. Maybe you can contact me privately and give me some details on what you would need.

Cheers,
Oscar

**Comment by hasindu2008** [comment]
On Twitter? Seems I cannot reach you there, possibly due to a setting. Could do on email if ou provide.

Also, if you are keen to try running, you can try the following steps:

```
git clone https://github.com/hasindu2008/f5c/ -b r10
autoreconf             
scripts/install-hts.sh  
./configure
make 
```

Then, run the test script for r10:
```
scripts/test_lsk114.sh
head test/hg2_lsk114_reads_1000/meth.tsv # to see if there are any calls
```

Then, you should specify the options models manually using options `--kmer-model test/r10-models/r10.4.1_400bps.nucleotide.9mer.template.model --meth-model test/r10-models/r10.4.1_400bps.cpg.9mer.template.model` to f5c.

**Comment by hasindu2008** [comment]
@ogrecio 

I have done a prerelease f5c-v1.2-beta with the r10 models inbuilt. Tested on some human data and got ~0.9 correlation with bisulphite data (without filtering). Great if you can run on your samples and check if you get more methylation sites.
