### ISSUE TITLE
Scale-events option info

### ISSUE THREAD

**Issue by F0nz0** [hasindu2008/f5c#128]
Good morning and thank you very much for your software again. 
I would like to receive some info related to the scale events parameter.
I'm interested in the retrieval of raw currents aligned to the reference genome. I used both scale-events and samples flags but I can't completely understand if I need to use also the scale events one. Is my decision to retrieve back raw currents in this way correct or I should avoid the scale-events flag in order to obtain the same current intensity values extracted from the corresponding fast5 file?

Thank you very much in advance

**Comment by hasindu2008** [comment]
Hi, --scale-events do not affect the signal samples printed. It only affects event_level_mean, model_mean and model_stdv. You can check [here](https://hasindu2008.github.io/f5c/docs/output#event-align) for some documentation.

Not that irrespective of --scale-events, the samples printed are not the raw ADC integer values in the FAST5, instead the raw integer values are converted to pico amperes and then scaled to fit the model (think of it as a form of normalisation to account for the effect of scale and the shift in the measured signal).

Is it the raw ADC integer values that you want to obtain?

**Comment by F0nz0** [comment]
Thank you very much for your answer. But I continue to don't get the point. You said --scale-events doesn't affect the printed samples but only the event_level_mean. Thus if I took the mean of the samples this should be different than the column event_level_mean when using the --scale-events. Instead I found the same mean. Or are the samples always scaled by default to the model? Furthermore in the documentation I found `--samples Prints the comma separated signal samples corresponding to the mapped k-mer (scaled pA current values). scaled pA current values = (pA - scaling.shift) / scaling.scale where pA = (raw_signal + offset) * range / digitisation`. I think there's somenthing I didn't understand. In the end, what I'm interested in is to retrieve back the samples but not scaled but simply the pA version (the same which I can calculate from ADC integers of fast5 by the means of both offset and digitisation).

I really appretiate your effort to clarify this question
Many thanks

**Comment by hasindu2008** [comment]
This example will help:
![image](https://user-images.githubusercontent.com/12987163/232954898-b9500ede-2872-476c-a562-3edcc28f084c.png)

As you can see, in both cases --samples are the same and the mean of those samples is always (101.659+103.189+101.999+102.509)/4=102.339. 

So irrespective of --scale-events, the printed signal samples are always scaled to the model. Equation `scaled pA current values = (pA - scaling.shift) / scaling.scale` gives how the picoampere signal is scaled to the model, `pA = (raw_signal + offset) * range / digitisation` is the equation that shows how the raw ADC values in the FAST5 file are converted to picoampere. So what is on the signal column is calculated by first converting the raw integer values to pico amperes, and then applying scaling parameters to scale to the model. Hope that is clear.

Currently,  there is no option to get the signal samples in pA without scaling in f5c. For this, one way is to specify --signal-index instead of --samples and based on the signal indexes extracting the raw samples from FAST5 files (you could easily do this with [S/BLOW5](https://www.nature.com/articles/s41587-021-01147-4) files than FAST5). I could implement an option otherwise, but I do not like this --samples options much in the first place, as the generated eventalign output file becomes gigantic.

ALso, can you tell me a bit about your use-case? I wonder if the signal samples for individual events that are not scaled to the model would be of broad use?

**Comment by F0nz0** [comment]
Ok...I have a better landscape undestanding of the situation now. Thank you so much! Is there a way to retrieve scaling.shift and scaling.scale to convert back to pA? I'm interested in building a training dataset to build some models.

**Comment by hasindu2008** [comment]
If you use the --summary option in event align, it will generate a summary file that has the shift and scale columns. So per each read ID you will know the shift and scale. Hope that helps.

However, in my experience, normalising is essential for typical signal analysis. For instance, ONT basecallers used to do some sort of zscore normalisation. Now they do some quantile scaling. If you use pure pA values, without the scaling applied, not sure if it will work for training.

**Comment by F0nz0** [comment]
I will try with the summary option. It seems to be exactly what I'm looking for.

 Yes, I'm absolutely in agree with you for the normalization but I've planned to try different normalization strategies starting from the pA values. 

Thank you for your precious help.

**Comment by hasindu2008** [comment]
Feel free to reopen if you have any more queries.

**Comment by IsisvanLoenen** [comment]
Hi, 
Could you tell me how the scaling and shift values are obtainend? If I'm looking per read-ID, I see that the scaling and shift values given by f5c eventalign --summary are different from the calibration offset and scale values within the original pod5 file. Thank you!

**Comment by IsisvanLoenen** [comment]
Thank you for your reply! For a read-id 'c534c9b3-0c30-46ba-83a2-510edca7f592', the pod5 file states (using Pod5Viewer):

- Calibration offset: 7.0
- Calibration scale: 0.17953379452228546
- Calibration_digitisation: 8192
- Calibration_range: 1470.7408447265625

![Image](https://github.com/user-attachments/assets/80dd3b89-e22d-4f90-9930-35f82de5238a)

The summary file of eventalign gives for this read:
- Shift: -9.796
- Scale: 0.966

![Image](https://github.com/user-attachments/assets/c0868965-68b4-4dc0-b674-35c55b7a07a9)

Could you explain to me why f5c eventalign does this estimation of the shift and scale using the  instead of using the values given in the pod5 file?

**Comment by hasindu2008** [comment]
`pA = (raw_signal + offset) * range / digitisation`

As you can see `offset` us now called `Calibration offset`. 
range / digitisation is `Calibration scale = Calibration_range/ Calibration_digitisation`

These POD5 calibration values are used in f5c (Calibration offset, Calibration_range and Calibration_digitisation ) to first convert the signal from raw signal values to pico amperes. Then, to scale the pA signal to the f5c model, a different scale and a shift are calculated inside f5c and used. You may refer to supplementary Note of f5c paper https://hasindu2008.github.io/f5c/nanopore_signal_alignment_supplementary_material.pdf 

The relavent section from:
![Image](https://github.com/user-attachments/assets/8c045978-9944-49b7-aae8-45f7d6c9607c)

**Comment by IsisvanLoenen** [comment]
Okay, so if I understand correctly without the --scale-events argument the pA event mean levels are already scaled using the calibration parameters given in the pod5 file, but when with --scale-events there is additional scaling using the scale and shift values given in the summary file.
Thank you for your explanation!
