### ISSUE TITLE
f5C eventalign with Guppy-called base modifications

### ISSUE THREAD

**Issue by ddubocan** [hasindu2008/f5c#144]
Hi,

Thanks for developing and supporting this tool.

Can `f5c eventalign` map raw signal back to basecalls if the basecalling was performed using guppy?
I am just a little lost as to where the signal information is coming from in this example:

`f5c eventalign -b chr22_meth_example/reads.sorted.bam -g chr22_meth_example/humangenome.fa -r chr22_meth_example/reads.fastq > chr22_meth_example/events.tsv
`

By default the bams produced by guppy don't encode the raw signal.

Best,
Danilo

**Comment by hasindu2008** [comment]
F5c needs the raw signal data. Do you have fast5 or blow5 or pod5 files of the datase

**Comment by ddubocan** [comment]
I converted fast5 to slow5 to get the signal data with --slow5 flag. Thanks!
reading through the documentation: https://hasindu2008.github.io/f5c/docs/output
I can't find anything detailing what the value for k actually is? Does K=6 or K=9? Additionally, do 0-indexed kmer positions refer to the beginning of the Kmer, or the base defined by that kmer? 

For example:

GCG**TTTATTT**GCG
for the kmer **TTTATTT**
is the position 3 or 6 that defines that kmer? 

My particular use case is to map the per-read raw signal directly back onto the basecalled reads (not reference).
It seems like manipulating the ss flag is the way to go for this -- I just want to make sure I am understanding how it is defined.

Is there any preference between resquiggle/eventalign or accompanying flags that you would recommend for this use case?

**Comment by hasindu2008** [comment]
Sorry, I missed the fact that you were trying to map raw signals to basecalled reads. In that case, you should use f5c resquiggle instead of f5c eventalign. Resquiggle will simply map the raw signal to the basecalled read and thus is exactly what you are looking for.

The value of k-mer depends on the model/chemistry: The built-in models for R10.4.1 9-mer, R9.4.1 DNA 6-mer and R9.4.1 RNA 5-mer. The k-mer position refers to the beginning of the k-mer. 

In your example, for GCGTTTATTTGCG, k-mer TTTATTT is of position 3.  The k-mer index always refers to the beginning of the k-mer. Infact mapping the signal to the read/reference has to be done at k-mer level, rather than individual base-level, because it is a k-mer that affects the instantaneous current

If you have anything requiring further clarification let me know.

**Comment by ddubocan** [comment]
Do you have any information / documentation on the SC and SH tag? Does that affect SS tag parsing and the signal that corresponds to a single kmer?

**Comment by hasindu2008** [comment]
Oh, I have missed documenting that, thanks for reporting. It does not affect parsing the ss tag. However, sc and sh are useful if you want to scale the raw signal values to the pore model (a kind of normalisation). I added a small description after the table at https://hasindu2008.github.io/f5c/docs/output#eventalign-tsv-output. Please see if it is clear.

**Comment by hasindu2008** [comment]
Closing the issue. Feel free to reopen if you have additional questions.
