### ISSUE TITLE
f5c support to event align for R10.4.1 RNA data?

### ISSUE THREAD

**Issue by kir1to455** [hasindu2008/f5c#150]
Hi,
Thank you for developing f5c!
I wonder know if f5c support to event align for R10.4.1 RNA data?
I can't find R10.4.1 RNA in the Readme.
![image](https://github.com/hasindu2008/f5c/assets/87375686/42c83f4e-2129-4fc8-bbd0-9c94f90c7ac8)

Best wishes,
Kirito

**Comment by hasindu2008** [comment]
You mean RNA004 I guess? Yes, a draft model is available and can be used as explained [here](https://github.com/hasindu2008/f5c/releases/tag/v1.3).

Still, I am in the process of fine-tuning the models and parameters. Once done, the fine-tuned model will be integrated into the tool itself and a direct option like --pore rna004 or something will be provided (and documented). 

You could test the draft model on the data you have and let me know your thoughts. So far, this draft model is already being used by [m6anet](https://github.com/GoekeLab/m6anet?tab=readme-ov-file#m6anet-model-trained-with-rna004-chemistry-development-version).

**Comment by kir1to455** [comment]
Brilliant! This is exactly what I need. Thanks for your reply so fast!

**Comment by Tang-pro** [comment]
@hasindu2008 
Hey

Could you please confirm if f5c now supports the RNA004 data? RNA004 provides POD5 files, which require conversion and are quite cumbersome to handle. If RNA004 is supported, would it be possible to analyze directly from POD5 files? Thank you!

**Comment by hasindu2008** [comment]
Hey @Tang-pro 

Yes, from a while a go RNA004 is supported in f5c. **f5c v1.4 onwards support nanopore RNA004 chemistry (make specify –pore rna004 if FAST5 input, autodetected for S/BLOW5 input**.

Unfortunately, haven't been able to implement POD5 support due to a number of reasons highlighted in https://github.com/hasindu2008/f5c/issues/190. I have been successfully converting POD5->BLOW5 using [blue-crab](https://github.com/Psy-Fer/blue-crab) for thousands of samples in the last couple of years.  Unless ONT did not do another change to the POD5 format structure,  the conversion should be handled by something like
```
blue-crab p2s input_pod5_dir -d output_blow5_dir 
```
Are we having issues with it?

**Comment by Tang-pro** [comment]
@hasindu2008 

Yes, when I converted POD5 to BLOW5 using blue-crab, I encountered an error: [ERROR]: acquisition_id does not match prev value. I have contacted the writer of blue-crab.

**Comment by Tang-pro** [comment]
@hasindu2008 

thank you!
