### ISSUE TITLE
RNA004 9-mer model

### ISSUE THREAD

**Issue by zhongzhd** [hasindu2008/f5c#160]
Hello,
First of all, thank you for creating f5c and for continuously updating it. I understand that f5c-v.1.4 includes an RNA004 9-mer model. Could you explain the difference between this and a 5-mer model? Thank you.

**Comment by hasindu2008** [comment]
Hello @zhongzhd 

Why I included a RNA004 9-mer model as default in 1.4 is due to two reasons
1. the 9-mer model was giving slightly better alignment results (I cannot remember the exact metrics off top my head, can dig my logs and give you if you would like)
2. to keep consistent with the k-mer size which ONT official k-mer models use at https://github.com/nanoporetech/kmer_models

**Comment by hasindu2008** [comment]
Closing this issue for now. If you have any more questions, feel free to reopen.
