### ISSUE TITLE
methylation calling is not supported for RNA data

### ISSUE THREAD

**Issue by yao-idol** [hasindu2008/f5c#162]
Hello,

We recently running f5c-1.4 on RNA004 data. We used the bam files from dorado basecalling. But then we have an error message:

[init_core::ERROR] Methylation calling is not supported for RNA data. 

The outputs for "f5c call-methylation" and "f5c meth-frq" are both empty tsv files. (but we do get result from "f5c eventalign".) What is the possible reason for this failure of methylation calling?

Thanks.

**Comment by hasindu2008** [comment]
Hello

f5c call-methylation, unfortunately, does not support methylation calling for RNA.  Methylation calling is available only for DNA.

Regards

**Comment by hasindu2008** [comment]
To add further, 
The reason is the lack of a trained methylated model for RNA. We do not have any control samples to train a methylated model for RNA. 
Eventalign works for both DNA and RNA because we have trained nucleotide models for those.
Hope I was clear. If not let me know so I can further explain.
