### ISSUE TITLE
No alignments after call methylation

### ISSUE THREAD

**Issue by CountBorgula** [hasindu2008/f5c#164]
I have now run into a new problem.  I have been following this tutorial with a subset of my own data (I couldn't download the sample data, I have e-mailed Professor Simpson about that).  I have now switched over to f5c, as my data was collected on R10 Minion flow-cell.

https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html

I run this command (sorry it is a bit long, I am doing everything on a large external mounted drive:

f5c_x86_64_linux_cuda call-methylation -t 8 -r fastq_runid_16ca937df17eefa9cbbb1909b7d37b0f851713f5_0_0.fastq.gz -
b output.sorted.bam -g /mnt/e/ONT_Data/ONT_comparing_raw_NA12878_to_PCR_direct_mC_detection/Nanopolish/Genome/GCF_000001405.40_GRCh38.p14_genomic.fasta > methylation_calls.tsv 

It all seems to run fine, but I get no methylation calls and it is apparently reporting that there were no alignments

[meth_main] skipped unmapped: 0, skipped secondary: 0, skipped low_mapq: 2022
[meth_main] total entries: 4185, qc fail: 0, could not calibrate: 0, no alignment: 4174, bad reads: 11

This is a sample of straight NA12878 DNA, so should have lots of methylation.

Thanks for any and all help.

Gary

**Comment by hasindu2008** [comment]
Hello, is this r9 data or r10 data?
If you are using fast5 as the input format and this is r10 data, you should specify the --pore r10 option to f5c manually.

**Comment by CountBorgula** [comment]
Ah, ok, will try that now.  Does your code work with pod5 without the need for that?

**Comment by CountBorgula** [comment]
That worked!

Ran:

f5c_x86_64_linux_cuda call-methylation --pore r10 -t 8 -r fastq_runid_16ca937df17eefa9cbbb1909b7d37b0f851713f5_0_0
.fastq.gz -b output.sorted.bam -g /mnt/e/ONT_Data/ONT_comparing_raw_NA12878_to_PCR_direct_mC_detection/Nanopolish/Genome/GCF_000001405.40_GRCh38.p14_genomic.fasta > methylation_calls.tsv

Lots of methylation reported!

[meth_main] skipped unmapped: 0, skipped secondary: 0, skipped low_mapq: 2022
[meth_main] total entries: 4185, qc fail: 9, could not calibrate: 0, no alignment: 2, bad reads: 11

**Comment by CountBorgula** [comment]
Thank you so much for your prompt reply!

**Comment by hasindu2008** [comment]
You can convert POD5 to BLOW5 format using the blue-crab https://github.com/Psy-Fer/blue-crab, and then merge it into a large blow5 using slow5tools merge. Then you can simply specify `--slow5 merged.blow5` to f5c.  I haven't implemented pod5 support for f5c, as ONT's POD5 format is utterly complex with too many dependencies (FAST5 turned out to be the hardest bit to maintain in f5c).

You can also convert the fast5->blow5 using slow5tools f2s and then merge using slow5tools merge. If you are running things from an external mount, having it converted to BLOW5 will make it many times faster than using fast5.
See https://hasindu2008.github.io/slow5tools/workflows.html: Methylation calling or eventalignment using f5c.
