### ISSUE TITLE
Matching format to nanopolish

### ISSUE THREAD

**Issue by LizzieMcDizzie** [hasindu2008/f5c#60]
Hi and thank you for such a useful tool. 
I was wondering if you would be able to make the headings of the outputs match: 

 f5c headings in tsv:
chromosome      start   end     read_name       log_lik_ratio   log_lik_methylated      log_lik_unmethylated    num_calling_strands     num_cpgs        sequence

Nanopolish headings in tsv:
chromosome      strand  start   end     read_name       log_lik_ratio   log_lik_methylated      log_lik_unmethylated    num_calling_strands     num_motifs      sequence

nanoploish freq table:
chromosome      start   end     num_motifs_in_group     called_sites    called_sites_methylated methylated_frequencygroup_sequence

f5c freq table:
chromosome      start   end     num_cpgs_in_group       called_sites    called_sites_methylated methylated_frequencygroup_sequence

It would be great if these were interchangeable.

Thanks again for the great tool.

Cheers.

**Comment by hasindu2008** [comment]
Thanks for reporting this and sorry for the slow response. 

The discrepancy between the _nanopolish_ output and _f5c_ output occurred because the output format in _f5c_ was based on initial _nanopolish_ versions, which the output format was like that then. It has eventually changed. In the latest _dev_ branch of the repository, I just fixed the issue. 

To keep the backward compatibility, the default output of _f5c call-methylation_ would be the older format, which you can specify to print the new version by the option _--meth-out-version=2_. _f5c meth-freq_ will find the output version of _f5c call-methylation_ by itself and print the header in the output accordingly.

Give it a try and let me know. I will merge the dev branch to the master branch in the coming days.
