### ISSUE TITLE
PromethION calls

### ISSUE THREAD

**Issue by andreaswallberg** [hasindu2008/f5c#83]
Dear @hasindu2008 ,

I am running f5c for a very large PromethION dataset. I am using the GPU version. It seems to be working alright on my workstation but I have realized I need faster and more disks to read from because most of the CPU and GPU is just waiting for new data to call.

Before I pursue this, I wonder if you can provide some feedback on calling methylation from PromethION data specifically. Are there particulars that I need to be aware of? Any settings or models or other parameters to use for this type of data vs minION?

**Comment by hasindu2008** [comment]
Hi @andreaswallberg 

Are you using the _--iop_ option? It is useful for any dataset (whether MinION or PromethION) if the data on a slow disk system.  On our server with a Tesla V100, I call with _-t 32_ and _--iop 64_, enabling a large PromethION set processing in like 10 hours.

**Comment by andreaswallberg** [comment]
Thanks for the feedback!

Well, I currently have 95% + 5% of the fast5 data (about 10 TB) on two separate slow traditional external USB harddrives. The best disk IO I can get with this setup seem to only be about 8-10MB/s, likely because of the extensive and nearly random movement of the hard drive headers across the fast5 collection. I have invested in some SSDs hoping to spread out the reads across as many disks as possible.

A mode that called reads sequentially in the order that they appear in the fast5 files instead of the genome and alignments could perhaps even be faster when disk IO is poor :-D

**Comment by hasindu2008** [comment]
@andreaswallberg 
_Well, I currently have 95% + 5% of the fast5 data (about 10 TB) on two separate slow traditional external USB harddrives. The best disk IO I can get with this setup seem to only be about 8-10MB/s, likely because of the extensive and nearly random movement of the hard drive headers across the fast5 collection._
If it is a single traditional spinning disk, random accesses would be extremely slow and with that 8-10MB/s sounds right.

 _I have invested in some SSDs hoping to spread out the reads across as many disks as possible._
SSDs, especially NVMes have amazing random access performance and even with just a single NVMe disk when f5c called with --iop 16 gives super-fast results. The downside is they are quite expensive for a massive storage size like 10 TB. Alternatively, do you have access to a NAS with multiple disks or a server with a RAID system where the storage can be mounted using NFS? I have tried both of those where the disks were spinning disks (12 spinning disks in the NAS and 10 spinning disks in the server) and f5c when called with --iop 64 could do a 2TB PromethION dataset in like 10 hours. Another option is using a cluster node with a shared cluster scratch storage as those systems are made of dozens of disks and the throughput is quite high. In our institute cluster with PANFS and NCI Gadi supercomputer I run f5c with _--iop 64_ and again a 2TB PromethION dataset can be done in like 8 hours. 

_A mode that called reads sequentially in the order that they appear in the fast5 files instead of the genome and alignments could perhaps even be faster when disk IO is poor :-D_
I thought about this in the past, but the challenge is we need to randomly fetch BAM entries based on reading ID (probably htslib supports this if the BAM file is sorted by readID instead of the genomic coordinates) and that requires a considerable source code modification. Even if such an optimisation is done, still the effort might be in vain because the FAST5 files (HDF5) seem to use a complex chunking system when storing data and thus reading just a single read requires multiple random accesses to the disk as I understand. Considering these, I never looked into implementing this approach, but I hope to look into it later (when I will get to do that is the problem :D)

**Comment by hasindu2008** [comment]
The latest f5c supports our SLOW5 file format. The benchmarks I did using external USB drives gave like 2X performance improvement for random access.  Please give it a try and let me know your thoughts.

Now the good thing is with SLOW5 sequential access can be implemented if needed (a lot of code refactoring though). Do you still have the performance bottleneck or did you procure faster drives?

**Comment by hasindu2008** [comment]
@andreaswallberg 
I am closing this issue for now. If you have any questions feel free to reopen it or start a new issue. Thanks.
